version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-browsers
      - image: circleci/python:2.7-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox

      - run:
          command: |
            . venv/bin/activate
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
